//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HillerService.DataMigration.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class DailyLog
    {
        public int id { get; set; }
        public string ServiceTradeId { get; set; }
        public string Description { get; set; }
        public System.DateTime TimeStamp { get; set; }
        public string logType { get; set; }
    
        public virtual STHookLog STHookLog { get; set; }
    }
}
