//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HillerService.DataMigration.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class STHookLog
    {
        public STHookLog()
        {
            this.DailyLog = new HashSet<DailyLog>();
        }
    
        public int LogID { get; set; }
        public Nullable<System.DateTime> TimeStamp { get; set; }
    
        public virtual ICollection<DailyLog> DailyLog { get; set; }
    }
}
